#!/usr/bin/env python3

import os, sys
from PIL import Image

directory = r'/home/student-01-1af4c0e9fe2f/supplier-data/images'

for file in os.listdir(directory):
  if 'tiff' in file:
    file_name = os.path.splitext(file)[0]
    im = Image.open(directory + "/" + file).convert("RGB").resize((600,400))
    im.save(directory + "/" + file_name + ".jpeg")

